/**:
  ros__parameters:
    # bare minimum for our diff-drive robot
    wheel_radius: 0.15
    wheel_width: 0.03
    front_overhang: 0.45  # between wheel center and vehicle front
    rear_overhang: 0.15   # between wheel center and vehicle rear
    vehicle_width: 0.50
    vehicle_length: 0.60  # front_overhang + rear_overhang
    vehicle_height: 0.50
    caster_wheel_radius: 0.08
    # vehicle_info_util requries these as of now
    # NOTE: this 0.080 may cause dangerous motion at high speed. in that case use 0.4
    wheel_base: 0.080 # between front wheel center and rear wheel center
    wheel_tread: 0.405 # between left wheel center and right wheel center
    left_overhang: 0.060 # between left wheel center and vehicle left
    right_overhang: 0.060 # between right wheel center and vehicle right
